import React, { useState, useEffect, useMemo, useRef } from "react";
import { User } from "firebase/auth";
import { Candidate, CandidateStageHistoryEntry, GeneralExpense, AgencySettings, ActiveView, StageId, PaymentRecord, ActivityLogEntry, ActivityActionType, ActivityCategory } from "./types";
import { STORAGE_KEYS, INITIAL_CANDIDATES, INITIAL_EXPENSES, DEFAULT_SETTINGS, STAGES, getTodayDateString, calculateCandidateFinance } from "./data/initialData";
import { TopBar, BottomBar, MobileQuickActionsSheet, MobileDrawer } from "./components/Navigation";
import { Dashboard } from "./components/Dashboard";
import { CandidateList } from "./components/CandidateList";
import { CandidateProfile } from "./components/CandidateProfile";
import { AddCandidateWizard } from "./components/AddCandidateWizard";
import { EditCandidateModal } from "./components/EditCandidateModal";
import { FinanceView } from "./components/FinanceView";
import { ArchiveView } from "./components/ArchiveView";
import { SettingsView } from "./components/SettingsView";
import { GlobalActivityLog } from "./components/GlobalActivityLog";
import { ReceiptModal, ReceiptData } from "./components/ReceiptModal";
import { GoogleSheetsModal } from "./components/GoogleSheetsModal";
import { GoogleCalendarModal } from "./components/GoogleCalendarModal";
import { ExportModal } from "./components/ExportModal";
import { PassportScannerModal } from "./components/PassportScannerModal";
import { InstallAppModal } from "./components/InstallAppModal";
import { LoginScreen } from "./components/LoginScreen";
import { AppUser, testFirebaseConnection, subscribeToAuth, subscribeToCandidates, syncCandidateToCloud, deleteCandidateFromCloud, syncAllCandidatesBatch, bulkArchiveCandidatesInCloud, subscribeToExpenses, syncExpenseToCloud, deleteExpenseFromCloud, syncAllExpensesBatch, subscribeToSettings, syncSettingsToCloud, subscribeToActivities, syncActivityToCloud, autoMigrateExistingDataToOwner } from "./lib/firebase";
import { createActivityEntry, buildHistoricActivitiesFromData } from "./lib/activityLog";
import { findCandidateDuplicates } from "./lib/candidateDuplicate";
import { Capacitor } from "@capacitor/core";
import { App as CapApp } from "@capacitor/app";
import { StatusBar, Style } from "@capacitor/status-bar";
import { SplashScreen } from "@capacitor/splash-screen";
import { ShieldCheck, Loader2 } from "lucide-react";

export default function App() {
  const [currentUser, setCurrentUser] = useState<User | AppUser | null>(null);
  const [authChecked, setAuthChecked] = useState(false);
  const migrationTriggeredRef = useRef(false);
  const [candidates, setCandidates] = useState<Candidate[]>(() => { try { const stored = localStorage.getItem(STORAGE_KEYS.candidates); if (stored) { const parsed = JSON.parse(stored); if (Array.isArray(parsed) && parsed.length > 0) return parsed; } } catch {} return INITIAL_CANDIDATES; });
  const [generalExpenses, setGeneralExpenses] = useState<GeneralExpense[]>(() => { try { const stored = localStorage.getItem(STORAGE_KEYS.expenses); if (stored) { const parsed = JSON.parse(stored); if (Array.isArray(parsed)) return parsed; } } catch {} return INITIAL_EXPENSES; });
  const [settings, setSettings] = useState<AgencySettings>(() => { try { const stored = localStorage.getItem(STORAGE_KEYS.settings); if (stored) return { ...DEFAULT_SETTINGS, ...JSON.parse(stored) }; } catch {} return DEFAULT_SETTINGS; });
  const [activities, setActivities] = useState<ActivityLogEntry[]>(() => { try { const stored = localStorage.getItem(STORAGE_KEYS.activities); if (stored) { const parsed = JSON.parse(stored); if (Array.isArray(parsed) && parsed.length > 0) return parsed; } } catch {} return buildHistoricActivitiesFromData(INITIAL_CANDIDATES, INITIAL_EXPENSES); });

  useEffect(() => { const unsubAuth = subscribeToAuth(user => { setCurrentUser(user); setAuthChecked(true); }); const safetyTimer = setTimeout(() => setAuthChecked(true), 5000); return () => { clearTimeout(safetyTimer); unsubAuth(); }; }, []);
  useEffect(() => { if (!currentUser || (currentUser as AppUser).isLocal) return; testFirebaseConnection(); if (!migrationTriggeredRef.current) { migrationTriggeredRef.current = true; autoMigrateExistingDataToOwner(currentUser.uid, candidates, generalExpenses, settings).catch(() => {}); } const unsubCandidates = subscribeToCandidates(currentUser.uid, cloud => { if (cloud) setCandidates(cloud); }); const unsubExpenses = subscribeToExpenses(currentUser.uid, cloud => { if (cloud) setGeneralExpenses(cloud); }); const unsubSettings = subscribeToSettings(currentUser.uid, cloud => { if (cloud && cloud.agencyName) setSettings(cloud); else syncSettingsToCloud(DEFAULT_SETTINGS, currentUser.uid); }); const unsubActivities = subscribeToActivities(cloud => { if (cloud && cloud.length > 0) setActivities(cloud); }); return () => { unsubCandidates(); unsubExpenses(); unsubSettings(); unsubActivities(); }; }, [currentUser]);

  const logActivity = (actionType: ActivityActionType, category: ActivityCategory, title: string, description: string, options?: { candidateId?: string; candidateName?: string; amount?: number; metadata?: Record<string, any> }) => { const email = currentUser?.email || "مدير النظام"; const entry = createActivityEntry(actionType, category, title, description, email, { userName: currentUser?.displayName || undefined, userUid: currentUser?.uid || undefined, ...options }); setActivities(prev => [entry, ...prev.slice(0, 999)]); syncActivityToCloud(entry).catch(() => {}); };

  const [currentView, setCurrentView] = useState<ActiveView>("dashboard");
  const [activeCandidateId, setActiveCandidateId] = useState<string | null>(null);
  const [showAddWizard, setShowAddWizard] = useState(false), [showEditModal, setShowEditModal] = useState(false), [receiptModalData, setReceiptModalData] = useState<ReceiptData | null>(null), [showReceiptModal, setShowReceiptModal] = useState(false), [showSheetsModal, setShowSheetsModal] = useState(false), [showGoogleCalendarModal, setShowGoogleCalendarModal] = useState(false), [showExportModal, setShowExportModal] = useState(false), [showPassportScanner, setShowPassportScanner] = useState(false), [showQuickHub, setShowQuickHub] = useState(false), [showMobileDrawer, setShowMobileDrawer] = useState(false), [showInstallModal, setShowInstallModal] = useState(false);
  const [exportDefaultTab, setExportDefaultTab] = useState<"CANDIDATES" | "FINANCE" | "PAYMENTS" | "EXPENSES">("CANDIDATES");
  useEffect(() => { try { localStorage.setItem(STORAGE_KEYS.candidates, JSON.stringify(candidates)); localStorage.setItem(STORAGE_KEYS.expenses, JSON.stringify(generalExpenses)); localStorage.setItem(STORAGE_KEYS.settings, JSON.stringify(settings)); localStorage.setItem(STORAGE_KEYS.activities, JSON.stringify(activities)); } catch {} }, [candidates, generalExpenses, settings, activities]);
  useEffect(() => { if (!Capacitor.isNativePlatform()) return; StatusBar.setStyle({ style: Style.Dark }).catch(() => {}); StatusBar.setBackgroundColor({ color: "#172a46" }).catch(() => {}); SplashScreen.hide().catch(() => {}); const listener = CapApp.addListener("backButton", () => { if (showAddWizard) return void setShowAddWizard(false); if (showEditModal) return void setShowEditModal(false); if (showReceiptModal) return void setShowReceiptModal(false); if (showSheetsModal) return void setShowSheetsModal(false); if (showGoogleCalendarModal) return void setShowGoogleCalendarModal(false); if (showExportModal) return void setShowExportModal(false); if (showPassportScanner) return void setShowPassportScanner(false); if (showQuickHub) return void setShowQuickHub(false); if (showMobileDrawer) return void setShowMobileDrawer(false); if (showInstallModal) return void setShowInstallModal(false); if (currentView === "profile") { setActiveCandidateId(null); setCurrentView("list"); return; } if (currentView !== "dashboard") { setCurrentView("dashboard"); return; } CapApp.exitApp(); }); return () => { listener.then(l => l.remove()).catch(() => {}); }; }, [showAddWizard, showEditModal, showReceiptModal, showSheetsModal, showGoogleCalendarModal, showExportModal, showPassportScanner, showQuickHub, showMobileDrawer, showInstallModal, currentView]);

  const alertCount = useMemo(() => { let count = 0; const now = Date.now(); candidates.filter(c => !c.archived).forEach(c => { if (c.passportExpiryDate && new Date(c.passportExpiryDate).getTime() - now < 180 * 86400000) count++; if (c.stage === "READY" && calculateCandidateFinance(c).outstanding > 0) count++; }); return count; }, [candidates]);
  const selectedCandidate = useMemo(() => activeCandidateId ? candidates.find(c => c.id === activeCandidateId) || null : null, [candidates, activeCandidateId]);

  const handleAddCandidate = (data: Partial<Candidate>, initialPayment?: { amount: number; method: any; note: string }) => {
    const duplicateCheck = findCandidateDuplicates(candidates, { firstName: data.firstName || "", lastName: data.lastName || "", dateOfBirth: data.dateOfBirth || "", passportNumber: data.passportNumber || "" });
    const confirmed = duplicateCheck.confirmed[0];
    if (confirmed) { alert(`⚠️ هذا المرشح مسجل مسبقًا.\n\nالاسم: ${confirmed.candidate.firstName} ${confirmed.candidate.lastName}\nرقم الجواز: ${confirmed.candidate.passportNumber || "غير مسجل"}\nالرقم الداخلي: ${confirmed.candidate.id}\n\nلن يتم إنشاء سجل مكرر.`); setActiveCandidateId(confirmed.candidate.id); setCurrentView("profile"); return; }
    const possible = duplicateCheck.possible[0];
    if (possible && !window.confirm(`⚠️ يوجد مرشح يحتمل أن يكون نفس الشخص.\n\nالاسم: ${possible.candidate.firstName} ${possible.candidate.lastName}\nتاريخ الميلاد: ${possible.candidate.dateOfBirth || "غير مسجل"}\nالرقم الداخلي: ${possible.candidate.id}\n\nهل تريد الاستمرار وتسجيله كمرشح جديد؟`)) { setActiveCandidateId(possible.candidate.id); setCurrentView("profile"); return; }
    const id = `CAND-${String(settings.nextId).padStart(4, "0")}`; const payments: PaymentRecord[] = initialPayment && initialPayment.amount > 0 ? [{ id: Date.now(), amount: initialPayment.amount, date: getTodayDateString(), method: initialPayment.method, note: initialPayment.note || "دفعة مقدمة عند التسجيل", receiptNumber: `REC-${String(Math.floor(1000 + Math.random() * 9000))}` }] : [];
    const uid = currentUser?.uid || "";
    const newCandidate: Candidate = { id, ownerUid: uid, firstName: data.firstName || "", lastName: data.lastName || "", phone: data.phone || "", secondPhone: data.secondPhone || "", gender: data.gender || "female", dateOfBirth: data.dateOfBirth || "", address: data.address || "", job: data.job || "", country: data.country || "المملكة العربية السعودية", passportNumber: data.passportNumber || "", passportExpiryDate: data.passportExpiryDate || "", agentName: data.agentName || "", sponsorName: data.sponsorName || "", stage: data.stage || "NEW", totalFees: Number(data.totalFees || 0), payments, expenses: [], registrationDate: getTodayDateString(), archived: false, medicalStatus: "لم يفحص", trainingStatus: "لم يبدأ", visaStatus: "لم تقدم", flightStatus: "لم تحجز بعد" };
    setCandidates(prev => [newCandidate, ...prev]); if (uid) syncCandidateToCloud(newCandidate, uid); setSettings(prev => { const updated = { ...prev, nextId: prev.nextId + 1, ownerUid: uid }; if (uid) syncSettingsToCloud(updated, uid); return updated; });
    const name = `${newCandidate.firstName} ${newCandidate.lastName}`.trim(); logActivity("CANDIDATE_CREATED", "CANDIDATE", `تسجيل مرشح جديد: ${name}`, `تم تسجيل المرشح ${name} برقم (${newCandidate.id})`, { candidateId: newCandidate.id, candidateName: name, amount: newCandidate.totalFees });
    if (payments.length) { const p = payments[0]; logActivity("PAYMENT_ADDED", "PAYMENT", `قبض دفعة تسجيل أولى: ${name}`, `تم استلام دفعة أولية بقيمة ${p.amount} عبر (${p.method || "كاش"})`, { candidateId: newCandidate.id, candidateName: name, amount: p.amount }); setReceiptModalData({ type: "PAYMENT", receiptNumber: p.receiptNumber || "REC-001", candidateName: name, candidateId: newCandidate.id, candidateJob: newCandidate.job, amount: p.amount, date: p.date, paymentMethod: p.method, note: p.note, remainingBalance: Math.max(0, newCandidate.totalFees - p.amount) }); setShowReceiptModal(true); }
    setActiveCandidateId(id); setCurrentView("profile");
  };

  const handleUpdateCandidate = (id: string, updates: Partial<Candidate>) => { const uid = currentUser?.uid || ""; setCandidates(prev => prev.map(c => { if (c.id !== id) return c; const name = `${c.firstName} ${c.lastName}`.trim(); let stageHistory = updates.stageHistory || c.stageHistory || []; if (updates.stage && updates.stage !== c.stage && !updates.stageHistory) { const fromLabel = STAGES.find(s => s.id === c.stage)?.label || c.stage; const toLabel = STAGES.find(s => s.id === updates.stage)?.label || updates.stage; const historyEntry: CandidateStageHistoryEntry = { id: "STG-" + Date.now().toString(36).toUpperCase() + Math.random().toString(36).substring(2, 5).toUpperCase(), fromStage: c.stage, toStage: updates.stage, date: new Date().toISOString(), timestamp: Date.now(), changedBy: currentUser?.email || "مدير النظام" }; stageHistory = [historyEntry, ...stageHistory]; logActivity("STAGE_CHANGE", "STAGE", `تغيير مرحلة: ${name} إلى ${toLabel}`, `تم تغيير مرحلة المرشح ${name} من [${fromLabel}] إلى [${toLabel}]`, { candidateId: c.id, candidateName: name }); }
      if (updates.payments && updates.payments.length > (c.payments?.length || 0)) { const p = updates.payments[updates.payments.length - 1]; logActivity("PAYMENT_ADDED", "PAYMENT", `سند قبض جديد: ${name}`, `تم استلام مبلغ ${p.amount} عبر (${p.method || "كاش"})${p.receiptNumber ? ` بسند رقم ${p.receiptNumber}` : ""}${p.note ? ` - ${p.note}` : ""}`, { candidateId: c.id, candidateName: name, amount: p.amount }); }
      if (updates.expenses && updates.expenses.length > (c.expenses?.length || 0)) { const e = updates.expenses[updates.expenses.length - 1]; logActivity("EXPENSE_CANDIDATE_ADDED", "EXPENSE", `مصروف على المرشح: ${name} (${e.category})`, `تم تسجيل مصروف بقيمة ${e.amount} لتغطية (${e.category})${e.note ? ` - ${e.note}` : ""}`, { candidateId: c.id, candidateName: name, amount: e.amount }); }
      if (updates.noteEntries && updates.noteEntries.length > (c.noteEntries?.length || 0)) { const n = updates.noteEntries[updates.noteEntries.length - 1]; logActivity("NOTE_ADDED", "DOCUMENT", `إضافة ملاحظة: ${name}`, `تمت كتابة ملاحظة توثيقية: "${n.text.slice(0, 70)}${n.text.length > 70 ? "..." : ""}"`, { candidateId: c.id, candidateName: name }); }
      const updated = { ...c, ...updates, stageHistory, ownerUid: uid || c.ownerUid, updatedAt: new Date().toISOString() }; if (uid) syncCandidateToCloud(updated, uid); return updated; })); };

  const handleArchiveCandidate = (id: string) => { const uid = currentUser?.uid || ""; const target = candidates.find(c => c.id === id); const name = target ? `${target.firstName} ${target.lastName}`.trim() : id; const updated = target ? { ...target, archived: true, ownerUid: uid || target.ownerUid, updatedAt: new Date().toISOString() } : null; setCandidates(prev => prev.map(c => c.id === id && updated ? updated : c)); if (uid && updated) syncCandidateToCloud(updated, uid); logActivity("CANDIDATE_ARCHIVED", "CANDIDATE", `أرشفة ملف المرشح: ${name}`, `تم نقل ملف المرشح ${name} إلى الأرشيف ومزامنة الحالة مع Cloud Firestore`, { candidateId: id, candidateName: name }); setCurrentView("list"); };
  const handleRestoreCandidate = (id: string) => { const uid = currentUser?.uid || ""; const target = candidates.find(c => c.id === id); const name = target ? `${target.firstName} ${target.lastName}`.trim() : id; const updated = target ? { ...target, archived: false, ownerUid: uid || target.ownerUid, updatedAt: new Date().toISOString() } : null; setCandidates(prev => prev.map(c => c.id === id && updated ? updated : c)); if (uid && updated) syncCandidateToCloud(updated, uid); logActivity("CANDIDATE_RESTORED", "CANDIDATE", `استعادة ملف المرشح: ${name}`, `تمت استعادة المرشح ${name} من الأرشيف`, { candidateId: id, candidateName: name }); };
  const handlePermanentDeleteCandidate = (id: string) => { const target = candidates.find(c => c.id === id); const name = target ? `${target.firstName} ${target.lastName}`.trim() : id; setCandidates(prev => prev.filter(c => c.id !== id)); if (activeCandidateId === id) setActiveCandidateId(null); deleteCandidateFromCloud(id); logActivity("CANDIDATE_DELETED", "CANDIDATE", `حذف نهائي لمرشح: ${name}`, `تم حذف ملف المرشح (${name}) برقم ${id} بشكل نهائي`, { candidateId: id, candidateName: name }); };
  const handleBulkArchiveCandidates = async (ids: string[]) => { if (!ids.length) return; const uid = currentUser?.uid || ""; const setIds = new Set(ids); let updated: Candidate[] = []; const names: string[] = []; setCandidates(prev => { updated = prev.map(c => setIds.has(c.id) ? { ...c, archived: true, ownerUid: uid || c.ownerUid, updatedAt: new Date().toISOString() } : c); updated.filter(c => setIds.has(c.id)).forEach(c => names.push(`${c.firstName} ${c.lastName}`.trim() || c.id)); return updated; }); if (uid) await bulkArchiveCandidatesInCloud(ids, uid, updated).catch(() => {}); logActivity("CANDIDATE_ARCHIVED", "CANDIDATE", `أرشفة مجمعة لـ (${ids.length}) من المرشحين`, `تمت أرشفة ملفات المرشحين [${names.slice(0, 3).join(", ")}${names.length > 3 ? ` وآخرين (+${names.length - 3})` : ""}]`, { candidateId: ids[0], candidateName: names.slice(0, 3).join(", "), metadata: { candidateIds: ids, count: ids.length } }); };
  const handleBulkChangeStageCandidates = (ids: string[], newStage: StageId) => { const uid = currentUser?.uid || ""; const setIds = new Set(ids); const changed = candidates.filter(c => setIds.has(c.id)); setCandidates(prev => prev.map(c => setIds.has(c.id) ? { ...c, stage: newStage, ownerUid: uid || c.ownerUid, updatedAt: new Date().toISOString() } : c)); if (uid && changed.length) syncAllCandidatesBatch(changed.map(c => ({ ...c, stage: newStage, ownerUid: uid, updatedAt: new Date().toISOString() })), uid); };
  const handleBulkDeleteCandidates = (ids: string[]) => { const setIds = new Set(ids); const targets = candidates.filter(c => setIds.has(c.id)); setCandidates(prev => prev.filter(c => !setIds.has(c.id))); ids.forEach(id => deleteCandidateFromCloud(id)); if (targets.length) logActivity("CANDIDATE_DELETED", "CANDIDATE", `حذف مجمع لـ (${targets.length}) من المرشحين`, `تم حذف ملفات المرشحين المحددين بشكل نهائي`, { candidateId: targets[0].id, candidateName: `${targets[0].firstName} ${targets[0].lastName}`.trim(), metadata: { candidateIds: ids, count: targets.length } }); };
  const handleAddGeneralExpense = (expense: Omit<GeneralExpense, "id">) => { const uid = currentUser?.uid || ""; const e: GeneralExpense = { ...expense, id: `EXP-${Date.now()}`, ownerUid: uid }; setGeneralExpenses(prev => [e, ...prev]); if (uid) syncExpenseToCloud(e, uid); logActivity("EXPENSE_GENERAL_ADDED", "EXPENSE", `مصروف تشغيلي عام: ${e.title}`, `تم تسجيل مصروف تشغيلي عام بقيمة ${e.amount} في بند (${e.category})${e.note ? ` - ${e.note}` : ""}`, { amount: e.amount }); };
  const handleDeleteGeneralExpense = (id: string | number) => { const stringId = String(id); const target = generalExpenses.find(e => String(e.id) === stringId); setGeneralExpenses(prev => prev.filter(e => String(e.id) !== stringId)); deleteExpenseFromCloud(stringId); if (target) logActivity("EXPENSE_GENERAL_DELETED", "EXPENSE", `حذف مصروف عام: ${target.title}`, `تم حذف المصروف العام بقيمة ${target.amount} (${target.category})`, { amount: target.amount }); };
  const handleSaveSettings = (newSettings: AgencySettings) => { const uid = currentUser?.uid || ""; const updated = { ...newSettings, ownerUid: uid }; setSettings(updated); if (uid) syncSettingsToCloud(updated, uid); logActivity("SETTINGS_UPDATED", "SETTINGS", "تحديث إعدادات الوكالة", `تم تعديل إعدادات الوكالة الرسمية (الاسم: ${newSettings.agencyName || "غير محدد"} - العملة: ${newSettings.currency})`); };
  const handleRestoreAllData = (data: { candidates: Candidate[]; generalExpenses: GeneralExpense[]; settings: AgencySettings }) => { const uid = currentUser?.uid || ""; const cs = data.candidates.map(c => ({ ...c, ownerUid: uid })); const es = data.generalExpenses.map(e => ({ ...e, ownerUid: uid })); const s = { ...data.settings, ownerUid: uid }; setCandidates(cs); setGeneralExpenses(es); setSettings(s); if (uid) { syncAllCandidatesBatch(cs, uid); syncAllExpensesBatch(es, uid); syncSettingsToCloud(s, uid); } logActivity("SETTINGS_UPDATED", "SETTINGS", "استعادة بيانات التطبيق", `تمت استعادة ${cs.length} مرشحًا و${es.length} مصروفات إلى الحساب السحابي`); };
  const handleResetToDemo = () => { const uid = currentUser?.uid || ""; const cs = INITIAL_CANDIDATES.map(c => ({ ...c, ownerUid: uid })); const es = INITIAL_EXPENSES.map(e => ({ ...e, ownerUid: uid })); const s = { ...DEFAULT_SETTINGS, ownerUid: uid }; setCandidates(cs); setGeneralExpenses(es); setSettings(s); if (uid) { syncAllCandidatesBatch(cs, uid); syncAllExpensesBatch(es, uid); syncSettingsToCloud(s, uid); } logActivity("SETTINGS_UPDATED", "SETTINGS", "إعادة بيانات العرض", `تمت إعادة بيانات التطبيق إلى مجموعة العرض الافتراضية (${cs.length} مرشحًا)`); };
  const handlePrintReceipt = (data: ReceiptData) => { setReceiptModalData(data); setShowReceiptModal(true); };
  const handleImportCandidatesFromSheets = (imported: Candidate[]) => { if (!imported.length) return; const uid = currentUser?.uid || ""; setCandidates(prev => { const ids = new Set(prev.map(c => c.id)); const next = [...prev]; imported.forEach(c => { const x = { ...c, ownerUid: uid }; const i = next.findIndex(n => n.id === c.id); if (i >= 0) next[i] = { ...next[i], ...x }; else if (!ids.has(c.id)) next.push(x); }); if (uid) syncAllCandidatesBatch(next, uid); return next; }); logActivity("CANDIDATE_CREATED", "CANDIDATE", `استيراد (${imported.length}) مرشح من Google Sheets`, `تم استيراد أو تحديث ${imported.length} سجلًا من Google Sheets`, { metadata: { count: imported.length } }); };

  if (!authChecked) return <div className="min-h-screen bg-[#0f1d31] flex flex-col items-center justify-center text-white"><div className="w-16 h-16 rounded-2xl bg-[#172a46] border-2 border-[#c9a84c] flex items-center justify-center mb-4 shadow-xl animate-pulse"><ShieldCheck className="w-8 h-8 text-[#c9a84c]" /></div><div className="flex items-center gap-2 text-stone-300 font-bold text-xs"><Loader2 className="w-4 h-4 animate-spin text-[#c9a84c]" /><span>جاري التحقق من أمان الجلسة والمصادقة...</span></div></div>;
  if (!currentUser) return <LoginScreen onSuccess={() => {}} />;

  return <div className="min-h-screen w-full max-w-full overflow-x-hidden bg-[#fdfcfb] text-[#1a1c1e] flex flex-col font-sans selection:bg-[#c9a84c]/20 selection:text-[#172a46]">
    <TopBar currentView={currentView} onNavigate={view => { setCurrentView(view); if (view !== "profile") setActiveCandidateId(null); }} onAddCandidate={() => setShowAddWizard(true)} onOpenGoogleSheetsModal={() => setShowSheetsModal(true)} onOpenGoogleCalendarModal={() => setShowGoogleCalendarModal(true)} onOpenPassportScanner={() => setShowPassportScanner(true)} onOpenExportModal={() => { setExportDefaultTab("CANDIDATES"); setShowExportModal(true); }} onOpenInstallModal={() => setShowInstallModal(true)} settings={settings} candidateCount={candidates.filter(c => !c.archived).length} alertCount={alertCount} currentUserEmail={currentUser?.email} onToggleMobileMenu={() => setShowMobileDrawer(v => !v)} />
    <main className="flex-1 w-full max-w-7xl mx-auto px-3 sm:px-6 lg:px-8 py-4 sm:py-6 overflow-x-hidden">
      {currentView === "dashboard" && <Dashboard candidates={candidates} generalExpenses={generalExpenses} settings={settings} onNavigate={setCurrentView} onSelectCandidate={id => { setActiveCandidateId(id); setCurrentView("profile"); }} onAddCandidate={() => setShowAddWizard(true)} onOpenGeneralExpenseModal={() => setCurrentView("finance")} onOpenExportModal={() => { setExportDefaultTab("FINANCE"); setShowExportModal(true); }} onOpenPassportScanner={() => setShowPassportScanner(true)} onOpenGoogleSheetsModal={() => setShowSheetsModal(true)} onOpenGoogleCalendarModal={() => setShowGoogleCalendarModal(true)} />}
      {currentView === "list" && <CandidateList candidates={candidates} settings={settings} onSelectCandidate={id => { setActiveCandidateId(id); setCurrentView("profile"); }} onAddCandidate={() => setShowAddWizard(true)} onEditCandidate={id => { setActiveCandidateId(id); setShowEditModal(true); }} onQuickStageChange={(id, stage) => handleUpdateCandidate(id, { stage })} onOpenExportModal={() => { setExportDefaultTab("CANDIDATES"); setShowExportModal(true); }} onBulkArchive={handleBulkArchiveCandidates} onBulkStageChange={handleBulkChangeStageCandidates} onBulkDelete={handleBulkDeleteCandidates} />}
      {currentView === "profile" && selectedCandidate && <CandidateProfile candidate={selectedCandidate} settings={settings} onBack={() => setCurrentView("list")} onUpdate={handleUpdateCandidate} onArchive={handleArchiveCandidate} onDelete={handlePermanentDeleteCandidate} onOpenEditModal={() => setShowEditModal(true)} onPrintReceipt={handlePrintReceipt} onOpenCalendarModal={() => setShowGoogleCalendarModal(true)} />}
      {currentView === "finance" && <FinanceView candidates={candidates} generalExpenses={generalExpenses} settings={settings} onAddGeneralExpense={handleAddGeneralExpense} onDeleteGeneralExpense={handleDeleteGeneralExpense} onOpenCandidateProfile={id => { setActiveCandidateId(id); setCurrentView("profile"); }} onOpenExportModal={tab => { setExportDefaultTab(tab || "FINANCE"); setShowExportModal(true); }} />}
      {currentView === "activity" && <GlobalActivityLog activities={activities} settings={settings} currentUserEmail={currentUser?.email} onSelectCandidate={id => { setActiveCandidateId(id); setCurrentView("profile"); }} onRefresh={() => { const stored = localStorage.getItem(STORAGE_KEYS.activities); if (stored) try { setActivities(JSON.parse(stored)); } catch {} }} />}
      {currentView === "archive" && <ArchiveView candidates={candidates} settings={settings} onRestore={handleRestoreCandidate} onPermanentDelete={handlePermanentDeleteCandidate} />}
      {currentView === "settings" && <SettingsView settings={settings} candidates={candidates} generalExpenses={generalExpenses} onSaveSettings={handleSaveSettings} onRestoreAllData={handleRestoreAllData} onResetToDemo={handleResetToDemo} onOpenGoogleSheetsModal={() => setShowSheetsModal(true)} />}
    </main>
    <BottomBar currentView={currentView} onNavigate={view => { setCurrentView(view); if (view !== "profile") setActiveCandidateId(null); }} onAddCandidate={() => setShowAddWizard(true)} onOpenGoogleSheetsModal={() => setShowSheetsModal(true)} onOpenPassportScanner={() => setShowPassportScanner(true)} onOpenExportModal={() => { setExportDefaultTab("CANDIDATES"); setShowExportModal(true); }} settings={settings} candidateCount={candidates.filter(c => !c.archived).length} alertCount={alertCount} currentUserEmail={currentUser?.email} onOpenQuickHub={() => setShowQuickHub(true)} onToggleMobileMenu={() => setShowMobileDrawer(true)} />
    <MobileQuickActionsSheet isOpen={showQuickHub} onClose={() => setShowQuickHub(false)} onAddCandidate={() => setShowAddWizard(true)} onOpenPassportScanner={() => setShowPassportScanner(true)} onOpenGoogleSheetsModal={() => setShowSheetsModal(true)} onOpenGoogleCalendarModal={() => setShowGoogleCalendarModal(true)} onOpenExportModal={() => { setExportDefaultTab("CANDIDATES"); setShowExportModal(true); }} onNavigate={view => { setCurrentView(view); if (view !== "profile") setActiveCandidateId(null); }} />
    <MobileDrawer isOpen={showMobileDrawer} onClose={() => setShowMobileDrawer(false)} currentView={currentView} onNavigate={view => { setCurrentView(view); if (view !== "profile") setActiveCandidateId(null); }} settings={settings} candidateCount={candidates.filter(c => !c.archived).length} currentUserEmail={currentUser?.email} onOpenPassportScanner={() => setShowPassportScanner(true)} onOpenGoogleSheetsModal={() => setShowSheetsModal(true)} onOpenGoogleCalendarModal={() => setShowGoogleCalendarModal(true)} onOpenExportModal={() => { setExportDefaultTab("CANDIDATES"); setShowExportModal(true); }} onOpenInstallModal={() => setShowInstallModal(true)} />
    <GoogleSheetsModal isOpen={showSheetsModal} onClose={() => setShowSheetsModal(false)} candidates={candidates} generalExpenses={generalExpenses} settings={settings} onImportCandidates={handleImportCandidatesFromSheets} />
    <GoogleCalendarModal isOpen={showGoogleCalendarModal} onClose={() => setShowGoogleCalendarModal(false)} candidates={candidates} onUpdateCandidate={handleUpdateCandidate} />
    <AddCandidateWizard isOpen={showAddWizard} onClose={() => setShowAddWizard(false)} onAdd={handleAddCandidate} settings={settings} />
    {selectedCandidate && <EditCandidateModal isOpen={showEditModal} onClose={() => setShowEditModal(false)} candidate={selectedCandidate} onSave={handleUpdateCandidate} />}
    <ReceiptModal isOpen={showReceiptModal} onClose={() => setShowReceiptModal(false)} receipt={receiptModalData} settings={settings} />
    <ExportModal isOpen={showExportModal} onClose={() => setShowExportModal(false)} candidates={candidates} generalExpenses={generalExpenses} settings={settings} defaultTab={exportDefaultTab} />
    <InstallAppModal isOpen={showInstallModal} onClose={() => setShowInstallModal(false)} />
    <PassportScannerModal isOpen={showPassportScanner} onClose={() => setShowPassportScanner(false)} onApplyData={data => { handleAddCandidate({ firstName: data.firstName, lastName: data.lastName !== "-" ? data.lastName : "", passportNumber: data.passportNumber, passportExpiryDate: data.passportExpiryDate, dateOfBirth: data.dateOfBirth, gender: data.gender, country: data.country, job: data.job || "عاملة منزلية" }); setShowPassportScanner(false); }} />
  </div>;
}